import { TPropertyType } from "@/enums/propertyType";
import { TOwner } from "@/interfaces/responses/ownerType";
import { TPhoto } from "@/interfaces/responses/photosType";
import { OwnershipType } from "@/enums/ownership";

export type TProperty = {
  id: string;
  createdAt: string;
  updatedAt: string;
  propertyType: TPropertyType;
  ownershipType: OwnershipType;
  price: number;
  address: string;
  city: string;
  state: string;
  zipCode: string;
  country: string;
  latitude: number;
  longitude: number;
  title: string;
  description: string;
  totalFloors: number;
  bedrooms: number;
  bathrooms: number;
  garages: number;
  squareMeters: number;
  yearBuilt: number;
  hasPool: boolean;
  hasGarden: boolean;
  hasSecurity: boolean;
  hasAirConditioning: boolean;
  hasWifi: boolean;
  hasTV: boolean;
  hasBalcony: boolean;
  hasParking: boolean;
  hasGarage: boolean;
  hasWasher: boolean;
  hasElevator: boolean;
  hasEquippedKitchen: boolean;
  ownerId: string;
  photos: TPhoto[];
  owner: TOwner;
};
