export type TPropertyType = {
  APARTMENT: "APARTMENT";
  HOUSE: "HOUSE";
  VILLA: "VILLA";
  RIAD: "RIAD";
  FARM: "FARM";
  STUDIO: "STUDIO";
  DUPLEX: "DUPLEX";
  TERRAIN: "TERRAIN";
  LOCAL_COMMERCIAL: "LOCAL_COMMERCIAL";
  BUREAU: "BUREAU";
  BUILDING: "BUILDING";
  ROOM: "ROOM";
  HOTEL: "HOTEL";
};

export enum EPropertyType {
  APARTMENT = "APARTMENT",
  HOUSE = "HOUSE",
  VILLA = "VILLA",
  RIAD = "RIAD",
  FARM = "FARM",
  STUDIO = "STUDIO",
  DUPLEX = "DUPLEX",
  TERRAIN = "TERRAIN",
  LOCAL_COMMERCIAL = "LOCAL_COMMERCIAL",
  BUREAU = "BUREAU",
  BUILDING = "BUILDING",
  ROOM = "ROOM",
  HOTEL = "HOTEL",
}
